<a href="https://colab.research.google.com/github/mafenavas/RGLABs-and-GLABs-Module-386/blob/main/m_navas_GLAB_386_3_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Guided LAB 386.3.5 - Exploratory Data Analysis on CSV data - Basic insights from the Data**
---

## **Lab Overview**

This lab focuses on introducing fundamental data analysis techniques using Python's Pandas library. We'll primarily work with a CSV file containing employee data, exploring various methods to load, manipulate, and gain insights from it.

In this lab, we will demonstrate how to read a CSV file with or without a header, skip rows, skip columns, set columns to index, and many more with examples. And we will perform Exploratory Data Analysis EDA on a CSV file.

**Key Activities:**

1. **Data Loading and Initial Exploration:**  We'll begin by importing the Pandas library and utilizing the `read_csv()` function to load the employee dataset into a Pandas DataFrame. We'll then use methods like `head()`, `tail()`, and `info()` to get an initial overview of the data's structure and content.
2. **Data Handling Techniques:** We will delve into practical data handling strategies, such as skipping rows or selecting specific columns during the data loading process using parameters like `skiprows` and `usecols` with `read_csv()`.
3. **Basic Exploratory Data Analysis (EDA):** We'll perform basic EDA to understand the dataset's characteristics. This includes examining data types, identifying potential missing values, and assessing the overall shape and size of the DataFrame.

**Learning Outcomes:**

By the end of this lab, you will be proficient in:

* Importing and utilizing the Pandas library in Google Colab.
* Loading CSV data into a Pandas DataFrame.
* Applying data manipulation techniques to extract desired information.
* Performing basic EDA to gain insights from datasets.

## **Introduction:**
Use the pandas read_csv() function to read a CSV file (comma-separated) into a Python pandas DataFrame. which supports options to read any delimited file.

##**Dataset:**
In this lab we will utilize the dummy employee dataset.

[Click here to download employee dataset (employee.csv)](https://drive.google.com/file/d/14RV1xKIRzWS166LtGqnPC1Wg7eTlI_y1/view?usp=drive_link)

---

# **Begin**

**Example 1: Reading Data from CSVs**

Note: if you get error, use the line below:
`df = pd.read_csv('employee.csv', on_bad_lines='skip')`

In [1]:
import pandas as pd
df = pd.read_csv('/content/employee.csv')
df

        Name   Age  Weight     Salary
0      James  36.0    75.0  5428000.0
1    Villers  38.0    74.0  3428000.0
2      VKole  31.0    70.0  8428000.0
3      Smith  34.0    80.0  4428000.0
4      Gayle  40.0   100.0  4528000.0
5       Adam  40.0     NaN  4528000.0
6     Rooter  33.0    72.0  7028000.0
7   Peterson  42.0    85.0  2528000.0
8      lynda  42.0    85.0        NaN
9        NaN  42.0    85.0        NaN
10     Jenny   NaN   100.0    25632.0
11      Kenn   NaN   110.0    25632.0
12       Aly   NaN    90.0    25582.0
13      John  41.0    85.0  1528000.0
14       Ali  26.0    69.0        NaN

Note: Use the sep or delimiter argument to specify the separator of the columns. By default, it uses a comma.

**Example 2: Viewing or Explore your Data**


The first thing to do when opening a new dataset is to print out a few rows to keep as a visual reference. We accomplish this with .head():

In [2]:
df.head()

      Name   Age  Weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

.head() outputs the first five rows of your DataFrame by default, but we could also pass a number as well. df.head(10) would output the top ten rows.

In [3]:

df.head(10)

       Name   Age  Weight     Salary
0     James  36.0    75.0  5428000.0
1   Villers  38.0    74.0  3428000.0
2     VKole  31.0    70.0  8428000.0
3     Smith  34.0    80.0  4428000.0
4     Gayle  40.0   100.0  4528000.0
5      Adam  40.0     NaN  4528000.0
6    Rooter  33.0    72.0  7028000.0
7  Peterson  42.0    85.0  2528000.0
8     lynda  42.0    85.0        NaN
9       NaN  42.0    85.0        NaN


To see the last five rows, use df.tail(), which also accepts a number and prints the bottom two rows in this case.

In [4]:
df.tail(2)

    Name   Age  Weight     Salary
13  John  41.0    85.0  1528000.0
14   Ali  26.0    69.0        NaN

**Example 3: Getting Information About your Data**

.info() should be one of the very first commands you run after loading your data:

In [5]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    14 non-null     object
 1   Age     12 non-null     float64
 2   Weight  14 non-null     float64
 3   Salary  12 non-null     float64
dtypes: float64(3), object(1)
memory usage: 612.0+ bytes

**.info()** provides the essential details about your dataset such as the number of rows and columns, the number of non-null values, what type of data is in each column, and how much memory your DataFrame is using.

Another fast and useful attribute is .shape, which returns just a tuple of (rows, columns):

In [6]:
df.shape

(15, 4)

Note that .shape has no parentheses and is a simple tuple format (rows, columns). So, we have 15 rows and 4 columns in our employeeDataFrame.

**Example 4: Lists all column headers in the DataFrame.**

df.columns is a Pandas attribute used to display the names of all columns in a DataFrame.

In [7]:
df.columns

Index(['Name', 'Age', 'Weight', 'Salary'], dtype='object')

**Common Uses for df.columns attribute:**

- View all column names.
- Verify that the expected columns exist.
- Check for spelling mistakes in column names.

**Example 5: Skip Rows**

Sometimes, you may need to skip the first row or skip the footer rows. To do this, use skiprows and skipfooter params, respectively.

In [8]:

# Skip first few rows
df = pd.read_csv('/content/employee.csv', header=None, skiprows=5)
print(df)

           0     1      2          3
0      Gayle  40.0  100.0  4528000.0
1       Adam  40.0    NaN  4528000.0
2     Rooter  33.0   72.0  7028000.0
3   Peterson  42.0   85.0  2528000.0
4      lynda  42.0   85.0        NaN
5        NaN  42.0   85.0        NaN
6      Jenny   NaN  100.0    25632.0
7       Kenn   NaN  110.0    25632.0
8        Aly   NaN   90.0    25582.0
9       John  41.0   85.0  1528000.0
10       Ali  26.0   69.0        NaN

**Example 6: Load Only Selected Columns**

There are two common ways to use this argument:

**Method 1:** Use usecols with Column Names

Syntax:
`df = pd.read_csv('my_data.csv', usecols=['column name one', 'column name two'])`

**Method 2:** Use usecols with Column Positions

Syntax:
`df = pd.read_csv('my_data.csv', usecols=[0, 2])`

In [9]:
pd.read_csv('/content/employee.csv', usecols=['Name', 'Salary'])

        Name     Salary
0      James  5428000.0
1    Villers  3428000.0
2      VKole  8428000.0
3      Smith  4428000.0
4      Gayle  4528000.0
5       Adam  4528000.0
6     Rooter  7028000.0
7   Peterson  2528000.0
8      lynda        NaN
9        NaN        NaN
10     Jenny    25632.0
11      Kenn    25632.0
12       Aly    25582.0
13      John  1528000.0
14       Ali        NaN

In [10]:
df = pd.read_csv('/content/employee.csv', usecols =[0,3])
print(df)

        Name     Salary
0      James  5428000.0
1    Villers  3428000.0
2      VKole  8428000.0
3      Smith  4428000.0
4      Gayle  4528000.0
5       Adam  4528000.0
6     Rooter  7028000.0
7   Peterson  2528000.0
8      lynda        NaN
9        NaN        NaN
10     Jenny    25632.0
11      Kenn    25632.0
12       Aly    25582.0
13      John  1528000.0
14       Ali        NaN

##**Submission**
- Submit your completed lab using the Start Assignment button on the assignment page in Canvas.
- Your submission can be include:
  - if you are using notebook then, all tasks should be written and submitted in a single notebook file, for example: (**your_name_labname.ipynb**).
  - if you are using python script file, all tasks should be written and submitted in a single python script file for example: **(your_name_labname.py)**.
- Add appropriate comments and any additional instructions if required.